--Crea la base de datos
Create Database VENTAS On (
	Name='VENTAS_DATA',
	Filename='c:\data\VENTAS_DATA.mdf',
	Size=15MB,
	Maxsize=200MB,
	Filegrowth=20%
),
(
	Name='VENTAS_SEC_001',
	Filename='c:\data\VENTA_SEC_001.ndf',
	Size=10MB,
	Maxsize=80MB,
	Filegrowth=2MB
)
Log on
(
	Name='VENTAS_Log',
	Filename='c:\data\VENTAS_Log.ldf',
	Size=10 MB,
	Maxsize=70 MB,
	Filegrowth=5 MB
)
Go
--Activa la base de datos
Use VENTAS
Go

--Crea la tabla distrito
Create Table DISTRITOS(
	COD_DIST CHAR(5)NOT NULL PRIMARY KEY,
	DESC_DIST VARCHAR(20)
)

--Crea la tabla EMPLEADO
Create Table EMPLEADOS(
	COD_EMP CHAR(5)NOT NULL PRIMARY KEY,
	NOM_EMP VARCHAR(30),
	APE_PAT_EMP VARCHAR(30),
	APE_MAT_EMP VARCHAR(30),
	FEC_NAC_EMP DATETIME,
	DIR_EMP VARCHAR(100),
	TEL_EMP CHAR(15),
	COD_DIST_EMP CHAR(5)REFERENCES DISTRITOS,
	CORREO_EMP VARCHAR(50),
	FEC_ING_EMP DATETIME,
	COD_SUPERVISOR CHAR(5)REFERENCES EMPLEADOS
)


--Crea la tabla cliente
Create Table CLIENTES(
	COD_CLI CHAR (5)NOT NULL PRIMARY KEY,
	DIR_CLI VARCHAR(50),
	TEL_CLI CHAR(15),
	COD_DIST_CLI CHAR(5)REFERENCES DISTRITOS,
	CORREO_CLI VARCHAR(30),
	WEB VARCHAR(50)
)
--Crea la tabla cliente persona jur�dica
Create Table CLIENTE_PER_JURIDICA
(
	COD_CLI CHAR(5)REFERENCES CLIENTES,
	RAZON_SOCIAL_CLI VARCHAR(100),
	RUC_CLI CHAR(11),
	CONTACTO_CLI VARCHAR(20),
	COD_CARGO_CLI CHAR(5),
	PRIMARY KEY (COD_CLI)
)
--Crea la tabla cliente persona natural
Create Table CLIENTE_PER_NATURAL
(
	COD_CLI CHAR(5)REFERENCES CLIENTES,
	NOM_CLI VARCHAR(100),
	APE_PAT_CLI VARCHAR(30),
	APE_MAT_CLI VARCHAR(30),
	PRIMARY KEY (COD_CLI)
)


--Crea la tabla tipo de producto
Create Table TIPO_PRODUCTO
(
	COD_TIPO_PROD CHAR(5)NOT NULL PRIMARY KEY,
	DESC_TIPO_PROD VARCHAR(50)
)
--Crea la tabla producto
Create table PRODUCTOS
(
	COD_PROD CHAR(5)NOT NULL PRIMARY KEY,
	DESC_PROD VARCHAR(50),
	PRECIO_PROD DECIMAL(9,2),
	STOCK_ACT_PROD INT,
	STOCK_MIN_PROD INT,
	COD_TIPO_PROD CHAR(5)REFERENCES TIPO_PRODUCTO
)
--Crea la tabla boleta
Create Table NOTAS
(
	COD_NOTA CHAR(5)NOT NULL PRIMARY KEY,
	COD_EMP CHAR(5)REFERENCES EMPLEADOS,
	FECHA_NOTA DATETIME,
	COD_CLI CHAR(5)REFERENCES CLIENTES,
	ESTADO_NOTA CHAR(10)
)
--Crea la taba detalle boleta
Create table DETALLENOTA
(
	COD_NOTA CHAR(5)REFERENCES NOTAS,
	COD_PROD CHAR(5)REFERENCES PRODUCTOS,
	CANTIDAD INT,
	PRECIO_VENTA DECIMAL(9,2)
	PRIMARY KEY(COD_NOTA,COD_PROD)
)

go


--1) InsertAMOS registros a todas las tablas.
INSERT INTO TIPO_PRODUCTO(COD_TIPO_PROD,DESC_TIPO_PROD) VALUES ('T0001','Leche y derivados');
INSERT INTO TIPO_PRODUCTO(COD_TIPO_PROD,DESC_TIPO_PROD) VALUES ('T0002','Carnes, pescados y huevos');
INSERT INTO TIPO_PRODUCTO(COD_TIPO_PROD,DESC_TIPO_PROD) VALUES ('T0003','Patatas, legumbres, frutos secos');
INSERT INTO TIPO_PRODUCTO(COD_TIPO_PROD,DESC_TIPO_PROD) VALUES ('T0004','Verduras y Hortalizas');
INSERT INTO TIPO_PRODUCTO(COD_TIPO_PROD,DESC_TIPO_PROD) VALUES ('T0005','Cereales y derivados, az�car y dulces');
INSERT INTO TIPO_PRODUCTO(COD_TIPO_PROD,DESC_TIPO_PROD) VALUES ('T0006','Grasas, aceite y mantequilla');
GO

INSERT INTO PRODUCTOS(COD_PROD,DESC_PROD,PRECIO_PROD,STOCK_ACT_PROD,STOCK_MIN_PROD,COD_TIPO_PROD)
VALUES ('P0001','Lechesfermentadas',10,100,50,'T0001');

INSERT INTO PRODUCTOS(COD_PROD,DESC_PROD,PRECIO_PROD,STOCK_ACT_PROD,STOCK_MIN_PROD,COD_TIPO_PROD)
VALUES ('P0002','Queso',8,100,50,'T0001');

INSERT INTO PRODUCTOS(COD_PROD,DESC_PROD,PRECIO_PROD,STOCK_ACT_PROD,STOCK_MIN_PROD,COD_TIPO_PROD)
VALUES ('P0003','Mantequilla',5,100,50,'T0001');

INSERT INTO PRODUCTOS(COD_PROD,DESC_PROD,PRECIO_PROD,STOCK_ACT_PROD,STOCK_MIN_PROD,COD_TIPO_PROD)
VALUES ('P0004','Yogur',5,100,50,'T0001');

INSERT INTO PRODUCTOS(COD_PROD,DESC_PROD,PRECIO_PROD,STOCK_ACT_PROD,STOCK_MIN_PROD,COD_TIPO_PROD)
VALUES ('P0005','Carne de vaca',50,100,50,'T0002');

INSERT INTO PRODUCTOS(COD_PROD,DESC_PROD,PRECIO_PROD,STOCK_ACT_PROD,STOCK_MIN_PROD,COD_TIPO_PROD)
VALUES ('P0006','Carne de cerdo',40,100,50,'T0002');

INSERT INTO PRODUCTOS(COD_PROD,DESC_PROD,PRECIO_PROD,STOCK_ACT_PROD,STOCK_MIN_PROD,COD_TIPO_PROD)
VALUES ('P0007','Carne de pollo',20,100,50,'T0002');

INSERT INTO PRODUCTOS(COD_PROD,DESC_PROD,PRECIO_PROD,STOCK_ACT_PROD,STOCK_MIN_PROD,COD_TIPO_PROD)
VALUES ('P0008','Pescado blanco',15,100,50,'T0002');

INSERT INTO PRODUCTOS(COD_PROD,DESC_PROD,PRECIO_PROD,STOCK_ACT_PROD,STOCK_MIN_PROD,COD_TIPO_PROD)
VALUES ('P0009','Pescado blanco',14,100,50,'T0002');
GO


INSERT INTO DISTRITOS (COD_DIST,DESC_DIST)VALUES ('D0001','Miraflores');
INSERT INTO DISTRITOS(COD_DIST,DESC_DIST) VALUES ('D0002','San Miguel');
INSERT INTO DISTRITOS(COD_DIST,DESC_DIST) VALUES ('D0003','San Luis');
INSERT INTO DISTRITOS(COD_DIST,DESC_DIST) VALUES ('D0004','Surco');
INSERT INTO DISTRITOS(COD_DIST,DESC_DIST) VALUES ('D0005','La Victoria');
INSERT INTO DISTRITOS(COD_DIST,DESC_DIST) VALUES ('D0006','El Agustino');
INSERT INTO DISTRITOS(COD_DIST,DESC_DIST) VALUES ('D0007','Comas');
GO
INSERT INTO EMPLEADOS(COD_EMP,NOM_EMP,APE_PAT_EMP,APE_MAT_EMP,FEC_NAC_EMP,DIR_EMP,TEL_EMP,COD_DIST_EMP,CORREO_EMP,FEC_ING_EMP,COD_SUPERVISOR)
VALUES ('E0001','Alexandre','Chavez','Costa','20000618 10:34:09 AM','Av. los amuletos 145','3781544','D0001','achavez@gmail.com','20120618 10:34:09 AM','E0001');
INSERT INTO EMPLEADOS(COD_EMP,NOM_EMP,APE_PAT_EMP,APE_MAT_EMP,FEC_NAC_EMP,DIR_EMP,TEL_EMP,COD_DIST_EMP,CORREO_EMP,FEC_ING_EMP,COD_SUPERVISOR)
VALUES ('E0002','David','Gomez','Costa','19900520','Av. loshidalgos145','3780544','D0002','davidgo@gmail.com','20190201','E0001');
INSERT INTO EMPLEADOS(COD_EMP,NOM_EMP,APE_PAT_EMP,APE_MAT_EMP,FEC_NAC_EMP,DIR_EMP,TEL_EMP,COD_DIST_EMP,CORREO_EMP,FEC_ING_EMP,COD_SUPERVISOR)
VALUES ('E0003','Julio','Sanches','Morales','19910130','Av. los risos 146','9681544','D0003','juliosa@gmail.com','20200120','E0001');
INSERT INTO EMPLEADOS(COD_EMP,NOM_EMP,APE_PAT_EMP,APE_MAT_EMP,FEC_NAC_EMP,DIR_EMP,TEL_EMP,COD_DIST_EMP,CORREO_EMP,FEC_ING_EMP,COD_SUPERVISOR)
VALUES ('E0004','Mayara','Farfan','Gallese','19950315','Av. las flores 148','3781534','D0004','mayfar@gmail.com','20190315','E0001');
INSERT INTO EMPLEADOS(COD_EMP,NOM_EMP,APE_PAT_EMP,APE_MAT_EMP,FEC_NAC_EMP,DIR_EMP,TEL_EMP,COD_DIST_EMP,CORREO_EMP,FEC_ING_EMP,COD_SUPERVISOR)
VALUES ('E0005','Raissa','Alves','Dias','19980610','Av. lascarmelitas 148','3770534','D0004','raissa@gmail.com','20180315','E0001');


INSERT INTO CLIENTES(COD_CLI,DIR_CLI,TEL_CLI,COD_DIST_CLI,CORREO_CLI,WEB)
VALUES ('C0001','Av. los risos 3993','2568566','D0001','josedelacruz@gmail.com',null);
INSERT INTO CLIENTES(COD_CLI,DIR_CLI,TEL_CLI,COD_DIST_CLI,CORREO_CLI,WEB)
VALUES ('C0002','Av. las flores 313','2365877','D0001',null,null);
INSERT INTO CLIENTES(COD_CLI,DIR_CLI,TEL_CLI,COD_DIST_CLI,CORREO_CLI,WEB)
VALUES ('C0003','Av. los girasoles 390','3214555','D0002',null,null);
INSERT INTO CLIENTES(COD_CLI,DIR_CLI,TEL_CLI,COD_DIST_CLI,CORREO_CLI,WEB)
VALUES ('C0004','Av. los pardos 159','3214599','D0003','gabomiranda@gmail.com',null);
INSERT INTO CLIENTES(COD_CLI,DIR_CLI,TEL_CLI,COD_DIST_CLI,CORREO_CLI,WEB)
VALUES ('C0005','Av. los cuadros 123','993626112','D0004','brendave@gmail.com',null);
INSERT INTO CLIENTES(COD_CLI,DIR_CLI,TEL_CLI,COD_DIST_CLI,CORREO_CLI,WEB)
VALUES ('C0006','Av. las petu�as3993','3245766','D0001','mercia@gmail.com','www.labodegademercia.com');
INSERT INTO CLIENTES(COD_CLI,DIR_CLI,TEL_CLI,COD_DIST_CLI,CORREO_CLI,WEB)
VALUES ('C0007','Av. las risas 313','993626145','D0001','osvaldoarcgmail.com','www.latienditadekarla.com');
INSERT INTO CLIENTES(COD_CLI,DIR_CLI,TEL_CLI,COD_DIST_CLI,CORREO_CLI,WEB)
VALUES ('C0008','Av. los pantanos 390','3214566','D0001','fechasa@gmail.com',null);
INSERT INTO CLIENTES(COD_CLI,DIR_CLI,TEL_CLI,COD_DIST_CLI,CORREO_CLI,WEB)
VALUES ('C0009','Av. los condes 159','993625145','D0002','elbrayan@gmail.com','www.eldiadito.com');
INSERT INTO CLIENTES(COD_CLI,DIR_CLI,TEL_CLI,COD_DIST_CLI,CORREO_CLI,WEB)
VALUES ('C0010','Av. los hidalgos 124','3217899','D0004','juanjo@gmail.com','www.laesquina.com');
GO
INSERT INTO CLIENTE_PER_NATURAL(COD_CLI,NOM_CLI,APE_PAT_CLI,APE_MAT_CLI)
VALUES ('C0001','Jos� Luis','De la Cruz','Villar');
INSERT INTO CLIENTE_PER_NATURAL(COD_CLI,NOM_CLI,APE_PAT_CLI,APE_MAT_CLI)
VALUES ('C0002','Maryllya','Fonseca','Alcarraz');
INSERT INTO CLIENTE_PER_NATURAL(COD_CLI,NOM_CLI,APE_PAT_CLI,APE_MAT_CLI)
VALUES ('C0003','Tatiana','Olivar','Mendoza');
INSERT INTO CLIENTE_PER_NATURAL(COD_CLI,NOM_CLI,APE_PAT_CLI,APE_MAT_CLI)
VALUES ('C0004','Gabriel','Miranda','Azul');
INSERT INTO CLIENTE_PER_NATURAL(COD_CLI,NOM_CLI,APE_PAT_CLI,APE_MAT_CLI)
VALUES ('C0005','Brenda','Vega','Carpio');
GO


INSERT INTO CLIENTE_PER_JURIDICA(COD_CLI,RAZON_SOCIAL_CLI,RUC_CLI,CONTACTO_CLI,COD_CARGO_CLI)
VALUES ('C0006','La bodega de M�rcia','12345678912',null,null);
INSERT INTO CLIENTE_PER_JURIDICA(COD_CLI,RAZON_SOCIAL_CLI,RUC_CLI,CONTACTO_CLI,COD_CARGO_CLI)
VALUES ('C0007','La tiendita de Karla','12345678913',null,null);
INSERT INTO CLIENTE_PER_JURIDICA(COD_CLI,RAZON_SOCIAL_CLI,RUC_CLI,CONTACTO_CLI,COD_CARGO_CLI)
VALUES ('C0008','La moradita','12345678914',null,null);
INSERT INTO CLIENTE_PER_JURIDICA(COD_CLI,RAZON_SOCIAL_CLI,RUC_CLI,CONTACTO_CLI,COD_CARGO_CLI)
VALUES ('C0009','El fiadito','12345678915',null,null);
INSERT INTO CLIENTE_PER_JURIDICA(COD_CLI,RAZON_SOCIAL_CLI,RUC_CLI,CONTACTO_CLI,COD_CARGO_CLI)
VALUES ('C0010','La esquina','12345678916',null,null);
GO
INSERT INTO NOTAS(COD_NOTA,COD_EMP,FECHA_NOTA,COD_CLI,ESTADO_NOTA)
VALUES ('B0001','E0002','20200101','C0001','Activo');
INSERT INTO NOTAS(COD_NOTA,COD_EMP,FECHA_NOTA,COD_CLI,ESTADO_NOTA)
VALUES ('B0002','E0002','20200101','C0002','Activo');
INSERT INTO NOTAS(COD_NOTA,COD_EMP,FECHA_NOTA,COD_CLI,ESTADO_NOTA)
VALUES ('B0003','E0002','20200102','C0003','Activo');
INSERT INTO NOTAS(COD_NOTA,COD_EMP,FECHA_NOTA,COD_CLI,ESTADO_NOTA)
VALUES ('B0004','E0004','20200101','C0004','Activo');
INSERT INTO NOTAS(COD_NOTA,COD_EMP,FECHA_NOTA,COD_CLI,ESTADO_NOTA)
VALUES ('B0005','E0004','20200101','C0005','Activo');
INSERT INTO NOTAS(COD_NOTA,COD_EMP,FECHA_NOTA,COD_CLI,ESTADO_NOTA)
VALUES ('B0006','E0003','20200101','C0006','Activo');
INSERT INTO NOTAS(COD_NOTA,COD_EMP,FECHA_NOTA,COD_CLI,ESTADO_NOTA)
VALUES ('B0007','E0003','20200101','C0007','Activo');
INSERT INTO NOTAS(COD_NOTA,COD_EMP,FECHA_NOTA,COD_CLI,ESTADO_NOTA)
VALUES ('B0008','E0003','20200102','C0008','Activo');
INSERT INTO NOTAS(COD_NOTA,COD_EMP,FECHA_NOTA,COD_CLI,ESTADO_NOTA)
VALUES ('B0009','E0003','20200102','C0009','Activo');
GO

INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0001','P0001',2,20);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0001','P0002',2,16);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0001','P0003',1,5);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0002','P0002',3,24);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0003','P0004',4,20);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0004','P0005',1,50);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0004','P0001',1,10);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0004','P0003',2,10);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0005','P0001',2,20);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0005','P0002',4,32);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0006','P0001',2,20);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0007','P0001',2,20);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0008','P0001',2,20);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0009','P0001',2,20);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0009','P0007',3,60);
INSERT INTO DETALLENOTA(COD_NOTA,COD_PROD,CANTIDAD,PRECIO_VENTA)
VALUES ('B0009','P0009',2,28);

--SELECT CAMPOS|* FROM nombre_tabla

select * from clientes

select nom_emp, APE_PAT_EMP from EMPLEADOS

select (APE_PAT_EMP+' '+NOM_EMP)as Nombre FROM EMPLEADOS

select * from empleados

select * from empleados
where APE_MAT_EMP='Costa'

/*Mostrar los empleados que su apellido paterno tenga Z*/
select * from empleados
where APE_PAT_EMP like '%z'

/*Mostrar los empleados que su telefono inicie con 2 o 3*/
select * from empleados
where TEL_EMP like'[2-3]%'

/*Mostrar los empleados que su telefono contenga un 8*/
select * from empleados
where TEL_EMP like '%8%'

Select * from productos


/*Mostrar la descripci�n de los productos cuyo precio esta entre 15 y 50*/
select desc_prod,PRECIO_PROD  from PRODUCTOS
where PRECIO_PROD between 15 and 50

select desc_prod,PRECIO_PROD  from PRODUCTOS
where PRECIO_PROD>=15 and PRECIO_PROD<=50



/*Mostrar la descripci�n de los productos y la decripcion del tipo cuyo precio esta entre 15 y 50
tipo 2 y es carde de pollo o de cerdo ordenarlos alfabeticamente*/

select desc_prod,PRECIO_PROD  from PRODUCTOS
where (PRECIO_PROD between 15 and 50) and COD_TIPO_PROD='T0002' 
and (DESC_PROD='Carne de pollo' or DESC_PROD='Carne de cerdo')
ORDER BY DESC_PROD DESC
----
select * from PRODUCTOS
SELECT * FROM TIPO_PRODUCTO

/*lISTA DE LOS PRODUCTOS con sus precios, la descripci�n del tipo de producto, 
odenados de menor a mayor precio*/

--PRODUCTO CARTESIANO
SELECT DESC_PROD,DESC_TIPO_PROD,PRECIO_PROD FROM PRODUCTOS,TIPO_PRODUCTO

--INNER JOIN
SELECT DESC_PROD,DESC_TIPO_PROD,PRECIO_PROD FROM PRODUCTOS,TIPO_PRODUCTO
WHERE  PRODUCTOS.COD_TIPO_PROD=TIPO_PRODUCTO.COD_TIPO_PROD   
ORDER BY PRECIO_PROD 

--INNER JOIN
/*Mostrar la descripci�n de los productos y la decripcion del tipo cuyo precio esta entre 15 y 50
tipo 2 y es carde de pollo o de cerdo ordenarlos alfabeticamente*/
SELECT DESC_PROD,DESC_TIPO_PROD,PRECIO_PROD FROM PRODUCTOS INNER JOIN TIPO_PRODUCTO
ON  PRODUCTOS.COD_TIPO_PROD=TIPO_PRODUCTO.COD_TIPO_PROD
where (PRECIO_PROD between 15 and 50) and PRODUCTOS.COD_TIPO_PROD='T0002' 
and (DESC_PROD='Carne de pollo' or DESC_PROD='Carne de cerdo')
ORDER BY PRECIO_PROD

/*Mostrar el nombre del cliente PERSONAS FISICAS y el nombre del distrito donde vive*/

select  nom_cli, desc_dist 
from  
    DISTRITOS inner join CLIENTES  ON DISTRITOS.COD_DIST=CLIENTES.COD_DIST_CLI
	INNER JOIN CLIENTE_PER_NATURAL ON CLIENTE_PER_NATURAL.COD_CLI=CLIENTES.COD_CLI

/*Mostrar el nombre del cliente PERSONAS JURIDICAS y el nombre del distrito donde SE ENCUENTRA*/

select  RAZON_SOCIAL_CLI, desc_dist 
from  
    DISTRITOS inner join CLIENTES  ON DISTRITOS.COD_DIST=CLIENTES.COD_DIST_CLI
	INNER JOIN CLIENTE_PER_JURIDICA ON CLIENTE_PER_JURIDICA.COD_CLI=CLIENTES.COD_CLI


select * from CLIENTES
select * from DISTRITOS
select * from CLIENTE_PER_JURIDICA


select  nom_cli AS 'Nombre del cliente', desc_dist as 'Distrito'
from  
    DISTRITOS inner join CLIENTES  ON DISTRITOS.COD_DIST=CLIENTES.COD_DIST_CLI
	INNER JOIN CLIENTE_PER_NATURAL ON CLIENTE_PER_NATURAL.COD_CLI=CLIENTES.COD_CLI
UNION
select  RAZON_SOCIAL_CLI,DESC_DIST
from  
    DISTRITOS inner join CLIENTES  ON DISTRITOS.COD_DIST=CLIENTES.COD_DIST_CLI
	INNER JOIN CLIENTE_PER_JURIDICA ON CLIENTE_PER_JURIDICA.COD_CLI=CLIENTES.COD_CLI

select productos.COD_PROD, desc_prod, CANTIDAD, PRECIO_VENTA 
from productos inner join detallenota on productos.cod_prod = detallenota.cod_prod
order by DESC_PROD

select DESC_PROD, CANTIDAD, PRECIO_VENTA, FECHA_NOTA, NOM_EMP
from productos inner join detallenota on productos.cod_prod = detallenota.cod_prod
			   inner join notas on notas.COD_NOTA = detallenota.COD_NOTA 
			   inner join EMPLEADOS on empleados.COD_EMP = notas.COD_EMP
order by fecha_nota, precio_venta

--TAREA
--Descripci�n del producto, cantidad que se vendi�, precio, fecha de la venta, nombre del empleado que realiz� la venta
--nombre y tel�fono del cliente
SELECT DESC_PROD, CANTIDAD, PRECIO_VENTA, FECHA_NOTA, NOM_EMP, NOM_CLI, TEL_CLI
FROM productos inner join detallenota on productos.cod_prod = detallenota.cod_prod
			   inner join notas on notas.COD_NOTA = detallenota.COD_NOTA 
			   inner join empleados on empleados.COD_EMP = notas.COD_EMP
			   inner join clientes on clientes.COD_CLI = notas.COD_CLI
			   inner join CLIENTE_PER_NATURAL on CLIENTE_PER_NATURAL.COD_CLI = clientes.COD_CLI

--Descripci�n del producto, descripci�n del tipo de producto, cantidad que se vendi�, precio, fecha de la venta,
--nombre del empleado que realiz� la venta y nombre y tel�fono del cliente.
SELECT DESC_PROD, DESC_TIPO_PROD, CANTIDAD, PRECIO_VENTA, FECHA_NOTA, NOM_EMP, NOM_CLI, TEL_CLI
FROM PRODUCTOS inner join TIPO_PRODUCTO on productos.COD_PROD = tipo_producto.COD_TIPO_PROD
			   inner join DETALLENOTA on productos.cod_prod = detallenota.cod_prod
			   inner join NOTAS on notas.COD_NOTA = detallenota.COD_NOTA 
			   inner join EMPLEADOS on empleados.COD_EMP = notas.COD_EMP
			   inner join CLIENTES on clientes.COD_CLI = notas.COD_CLI
			   inner join CLIENTE_PER_NATURAL on CLIENTE_PER_NATURAL.COD_CLI = clientes.COD_CLI 

--Descripci�n del producto, descripci�n del tipo de producto, cantidad que se vendi�, precio, fecha de la venta, nombre del 
--empleado que realiz� la venta, nombre telefono y descripci�n del distrito del cliente.
SELECT DESC_PROD, DESC_TIPO_PROD, CANTIDAD, PRECIO_VENTA, FECHA_NOTA, NOM_EMP, NOM_CLI, TEL_CLI
FROM PRODUCTOS inner join TIPO_PRODUCTO on productos.COD_PROD = tipo_producto.COD_TIPO_PROD
			   inner join DETALLENOTA on productos.cod_prod = detallenota.cod_prod
			   inner join NOTAS on notas.COD_NOTA = detallenota.COD_NOTA 
			   inner join EMPLEADOS on empleados.COD_EMP = notas.COD_EMP
			   inner join CLIENTES on clientes.COD_CLI = notas.COD_CLI
			   inner join CLIENTE_PER_NATURAL on CLIENTE_PER_NATURAL.COD_CLI = clientes.COD_CLI
			   inner join DISTRITOS on distritos.COD_DIST = CLIENTES.COD_DIST_CLI